# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Anchors and Alias
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

# Re-usuable commands.
commands:
  sayhello:
    description: " A very simple command for demonstrating the purposes for commands"
    parameters:
      to:
        type: string
        default: "Hello world"
    steps:
      - run: echo << parameters.to >>

jobs:
  save_hello_world_output:
    <<: *defaults
    steps:
      - run: echo "Hello kartik, this is called sharing files" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  # adding another job to check the commands fucntionality
  checkcommand:
    <<: *defaults
    steps:
      - sayhello:
          to: "Congrats! you have sucessfully implemented Commands, Anchors and Alias."
  # Roll back code to clean up when build fails.
  checkRollBack:
    <<: *defaults
    steps:
      - run: return 1
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - checkcommand:
          requires:
            - print_output_file
      - checkRollBack:
          requires:
            - checkcommand:
